default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reporter

test:
  <<: *default
  database: reporter_test

production:
  <<: *default
  database: reporter
